### ISSUE TITLE
Unable to find title

### ISSUE THREAD

**Issue by Shizmob** [chikorita157/malupdaterosx-cocoa#16]
Trying to scrobble Minami-ke for testing (`Minami-ke 01 [Minami] [5ADB3708].mkv`), using mpv (compiled via Homebrew, `mpv 0.11.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects`), MAL Updater OSX tells me it can't find the title, and shows an empty title suggestion list.
Here's the console log:

```
10/03/16 17:59:22,578 MAL Updater OS X[6292]: Starting...
10/03/16 17:59:22,791 MAL Updater OS X[6292]: Updating Auto Exceptions!
10/03/16 17:59:22,893 MAL Updater OS X[6292]: Check Exceptions List
10/03/16 17:59:22,893 MAL Updater OS X[6292]: Checking Auto Exceptions
10/03/16 17:59:22,894 MAL Updater OS X[6292]: =============
10/03/16 17:59:22,895 MAL Updater OS X[6292]: Scrobbling...
10/03/16 17:59:22,895 MAL Updater OS X[6292]: Finding AniID
10/03/16 17:59:22,895 MAL Updater OS X[6292]: Searching For Title
10/03/16 17:59:25,220 MAL Updater OS X[6292]: Title is not a movie.
10/03/16 17:59:25,221 MAL Updater OS X[6292]: Error: Couldn't find title Minami-ke. Please add an Anime Exception rule.
10/03/16 17:59:25,221 MAL Updater OS X[6292]: Scrobble Complete with Status Code: 51
10/03/16 17:59:25,221 MAL Updater OS X[6292]: =============
10/03/16 17:59:28,253 MAL Updater OS X[6292]: Stopping Auto Scrobble.
```

It's definitely on MAL: http://myanimelist.net/anime.php?q=minami-ke

**Comment by chikorita157** [comment]
Looks like atarashii-api broke due to changes on MyAnimeList. I will update atarashii-api to see if it works now

**Comment by chikorita157** [comment]
It's fixed. 

`[{"id":14575,"title":"Minami-ke Omatase","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/8\/53131t.jpg","type":"OVA","episodes":1,"status":null,"start_date":"2012-10-05","end_date":"2012-10-05","classification":"PG-13","members_score":7.48,"members_count":null,"favorited_count":null,"synopsis":"Minami-ke OVA bundled with the 10th volume of the manga.","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":20221,"title":"Minami-ke Natsuyasumi","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/5\/64505t.jpg","type":"OVA","episodes":1,"status":null,"start_date":"2013-08-06","end_date":"2013-08-06","classification":"PG-13","members_score":7.45,"members_count":null,"favorited_count":null,"synopsis":"Second Minami-ke OVA bundled with the 11th volume of the manga. Chiaki, Kana, and Haruka decide how to spend their last few days of summer together. Kana struggles to finish her homework.","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":2963,"title":"Minami-ke","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/2\/75279t.jpg","type":"TV","episodes":13,"status":null,"start_date":"2007-10-08","end_date":"2007-12-31","classification":"PG-13","members_score":7.85,"members_count":null,"favorited_count":null,"synopsis":"There are three of the Minami sisters: Haruka, Kana and Chiaki, who have an average life. The girls only have each other to depend on and help each other get through everything from love confessions t...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":3225,"title":"Minami-ke Okawari","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/10\/73556t.jpg","type":"TV","episodes":13,"status":null,"start_date":"2008-01-07","end_date":"2008-03-31","classification":"PG-13","members_score":7.43,"members_count":null,"favorited_count":null,"synopsis":"The second season of Minami-Ke. It picks up where the first season left off, and just like the first season, it's about the daily lives of the three Minami sisters, Haruka, Kana and Chiaki, and their...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":14511,"title":"Minami-ke Tadaima","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/7\/53133t.jpg","type":"TV","episodes":13,"status":null,"start_date":"2013-01-06","end_date":"2013-03-31","classification":"PG-13","members_score":7.8,"members_count":null,"favorited_count":null,"synopsis":"The everyday lives of the Minami sisters continue. Chiaki, the youngest, continues to call people idiots while worshipping her eldest sister. Kana, the middle, still can't figure out that Fujioka's fe...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":5162,"title":"Minami-ke Okaeri","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/10\/11458t.jpg","type":"TV","episodes":13,"status":null,"start_date":"2009-01-05","end_date":"2009-03-30","classification":"PG-13","members_score":7.67,"members_count":null,"favorited_count":null,"synopsis":"A year has passed since \"Okawari\" and the three sisters have grown up. Their likings and moods are almost the same. Haruka, the older sister, is a love-giving mother to the younger sisters and a disci...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":5713,"title":"Minami-ke Betsubara","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/10\/25454t.jpg","type":"OVA","episodes":1,"status":null,"start_date":"2009-06-23","end_date":"2009-06-23","classification":"PG-13","members_score":7.58,"members_count":null,"favorited_count":null,"synopsis":"Valentine's Day is approaching; Hosaka is still trying to express his love to Haruka by cooking, cross-dressing Mako-chan fears to be found out, Kana-\"sensei\" teaches the other girls how to \"win\" Vale...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":23399,"title":"Minami no Shima no Dera-chan","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/6\/60437t.jpg","type":"Movie","episodes":1,"status":null,"start_date":"2014-04-26","end_date":"2014-04-26","classification":"PG-13","members_score":6.54,"members_count":null,"favorited_count":null,"synopsis":"The story follows Dera after he returns to the southern islands from the Usagiyama Shopping District, and depicts his gentle slapstick daily life with the Prince and Choi. (Source: ANN)","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":2573,"title":"Minami no Niji no Lucy","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/12\/3360t.jpg","type":"TV","episodes":50,"status":null,"start_date":"1982-01-10","end_date":"1982-12-26","classification":"G","members_score":7.06,"members_count":null,"favorited_count":null,"synopsis":"Lucy's family moves from England to Australia planning to run a big farm. Starting a new life proves to be full of frustrations. Their agonizing days of despair continue until they finally obtain thei...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":6688,"title":"Batain Lai!! Minami no Shima no Mizu Monogatari","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/6\/15373t.jpg","type":"Movie","episodes":1,"status":null,"start_date":"2009-05-09","end_date":"2009-05-09","classification":"G","members_score":6.38,"members_count":null,"favorited_count":null,"synopsis":"The film was directed by Noboru Ishiguro (The Super Dimension Fortress Macross) and is based on the true story of Yoichi Hatta (1886-1942), a civil engineer who traveled to Japanese-ruled Taiwan in 19...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":32475,"title":"Minami no Kuni kara Kita Tegami","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/3\/77924t.jpg","type":"Music","episodes":1,"status":null,"start_date":null,"end_date":null,"classification":"G","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"A music video for the song \"Minami no Kuni kara Kita Tegami\" by Akane Oda. Aired as part of NHK's Minna no Uta program.","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":31422,"title":"Minami Kamakura Koukou Joshi Jitensha-bu","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/8\/75746t.jpg","type":"TV","episodes":0,"status":null,"start_date":null,"end_date":null,"classification":"PG-13","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"Maiharu Hiromi has moved to Kamakura Nagasaki, and rides a bicycle to school everyday. Then she meets Akizuki Tomoe, the leader of the girls cycling club. She therefore joins the club and her life gra...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":25071,"title":"Minami no Niji no Lucy Specials","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/12\/64131t.jpg","type":"Special","episodes":2,"status":null,"start_date":null,"end_date":null,"classification":"G","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"A summary of the Minami no Niji no Lucy full series aired as a TV specials.","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":9316,"title":"Toushindai My Lover: Minami tai Mecha-Minami","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/5\/25822t.jpg","type":"OVA","episodes":1,"status":null,"start_date":"2001-10-26","end_date":"2001-10-26","classification":"Rx","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"A young man receives a life-size nude girl in the mail. Not knowing where she came from or who sent her, he tries to figure things out when his little sister, Minami, arrives home. Needless to say, Mi...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":18479,"title":"Bishoujo Animerama: Minami no Watashi no Heart ni Tacchi Shite...","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/9\/49453t.jpg","type":"OVA","episodes":1,"status":null,"start_date":null,"end_date":null,"classification":"Rx","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"A mix of animation and live-action.","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":18631,"title":"Naniwa Kinyuu Den: Minami no Teiou","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/4\/49763t.jpg","type":"OVA","episodes":2,"status":null,"start_date":"1993-09-22","end_date":"1994-05-27","classification":"R+","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"The story centers around Ginjirou Manda, a loan shark who charges toichi \u2014 10% more interest every 10 days, or 365% every year. Thanks to his unrelenting money-collecting tactics, he is feared as Mina...","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":21291,"title":"Sore Ike! Anpanman: Minami no Umi wo Sukue!","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/4\/56227t.jpg","type":"Special","episodes":1,"status":null,"start_date":"1990-08-26","end_date":"1990-08-26","classification":"PG","members_score":0,"members_count":null,"favorited_count":null,"synopsis":null,"genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null},{"id":10563,"title":"Yakyuukyou no Uta: Kita no Ookami Minami no Tora","other_titles":{},"rank":null,"popularity_rank":null,"image_url":"http:\/\/cdn.myanimelist.net\/images\/anime\/9\/29016t.jpg","type":"Movie","episodes":1,"status":null,"start_date":"1979-09-15","end_date":"1979-09-15","classification":"PG-13","members_score":0,"members_count":null,"favorited_count":null,"synopsis":"A re-edited version of episodes 13 and 14 of the TV series. Double billed with Mirai Shounen Conan movie in the cinemas. (Source: AniDB)","genres":[],"tags":[],"manga_adaptations":[],"prequels":[],"sequels":[],"side_stories":[],"parent_story":null,"character_anime":[],"spin_offs":[],"summaries":[],"alternative_versions":[],"watched_status":null,"watched_episodes":null,"score":null,"listed_anime_id":null}]`

**Comment by Shizmob** [comment]
Thanks!
