### ISSUE TITLE
Issues with CrunchyRoll

### ISSUE THREAD

**Issue by DeSailor** [chikorita157/malupdaterosx-cocoa#7]
Hey there, Chikorita! 

Seems I'm having a few issues with CrunchyRoll today. At first I thought it was because I had mpv open with Space Dandy, but after closing that, it seems it's an issue with CrunchyRoll. 

No crashes or anything, but, this is all that shows up in the console: 

3/8/15 3:10:04.060 PM MAL Updater OS X[3026]: Starting...

Just that, nothing else. 

I tested this with two shows on CrunchyRoll (not like it should matter): Fate/Stay Night & Durarara x2

**Comment by chikorita157** [comment]
I have run detectstream on my side and here is the result:
{"result":[{"browser":"Safari","title":"Fate\/stay night","season":1,"site":"crunchyroll","episode":7}]}

2015/03/08 17:55:29.477 MAL Updater OS X[73205]: =============
2015/03/08 17:55:29.477 MAL Updater OS X[73205]: Scrobbling...
2015/03/08 17:55:29.478 MAL Updater OS X[73205]: Finding AniID
2015/03/08 17:55:29.478 MAL Updater OS X[73205]: Searching For Title
2015/03/08 17:55:31.231 MAL Updater OS X[73205]: Title is not a movie.
2015/03/08 17:55:31.232 MAL Updater OS X[73205]: Valid Episode Count
2015/03/08 17:55:31.233 MAL Updater OS X[73205]: Found 356
2015/03/08 17:55:31.233 MAL Updater OS X[73205]: Checking Status
2015/03/08 17:55:32.588 MAL Updater OS X[73205]: Not on List
2015/03/08 17:55:32.588 MAL Updater OS X[73205]: Adding Title
2015/03/08 17:55:32.588 MAL Updater OS X[73205]: Scrobble Complete with Status Code: 3
2015/03/08 17:55:32.589 MAL Updater OS X[73205]: =============

It works fine in my side... Make sure you don't have any player open in Activity Monitor. Otherwise, it won't check for stream... Also, make sure you are using compatible browsers.

**Comment by DeSailor** [comment]
Hi there. 

This is from Console: 

3/8/15 9:28:09.785 PM MAL Updater OS X[572]: Starting...
3/8/15 9:28:09.971 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.971 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.972 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.979 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.980 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.981 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.982 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.983 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.983 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread
3/8/15 9:28:09.984 PM Safari[497]: An exception was thrown during execution of an NSScriptCommand...
3/8/15 9:28:09.984 PM Safari[497]: [<CompletionWindow 0x7fe15ae8ddc0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key orderedTabViewItems.
3/8/15 9:28:09.984 PM detectstream[657]: AppleEvents: Send port for process has no send right, port=( port:23823/0x5d0f rcv:1,send:0,d:0 limit:5) (findOrCreate()/AEMachUtils.cp #526) com.apple.main-thread

When I click 'update' on CrunchyRoll. 

Now on detectstream I get this: 

 Matt$ /Applications/MAL\ Updater\ OS\ X.app/Contents/Resources/detectstream ; exit;
{"result":null}
logout

[Process complete]

**Comment by chikorita157** [comment]
Can you give me the page URL where you are having problems?

**Comment by DeSailor** [comment]
Here you are: http://www.crunchyroll.com/durarara/episode-8-the-ladies-man-has-neither-money-nor-power-668083?t=119

It's not just this one though, It's all CrunchyRoll videos. 

I've tried: 

- Fate/Stay Night 
- Your Lie in April
- Durarara
- Sailor Moon Crystal

**Comment by chikorita157** [comment]
I figured out the problem... It doesn't seem to like the ?t=119... I'll fix it in the next build.

**Comment by DeSailor** [comment]
That's weird, but thank you.

**Comment by chikorita157** [comment]
It was a regex boo boo... It's fixed with https://github.com/Atelier-Shiori/detectstream/commit/5658d9c92bb9bfe6d2737dc8b2abd9347c300175
